# Broadcasting in Python
> Example: Calories from Carbs, Proteins, and Fats in 100g of different foods.

## Initialising Array

In [12]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.8],
              [1.2, 104.0, 52.0, 8.0],
              [1.0, 135.0, 99.0, 0.9]])

B = np.array([[1], [2], [3]])

print(str(A))

C = A * B
C.shape

[[ 56.    0.    4.4  68.8]
 [  1.2 104.   52.    8. ]
 [  1.  135.   99.    0.9]]


(3, 4)

In [31]:
a=np.random.randn(1,3) # a.shape=(1,3)
b=np.random.randn(3,3) # b.shape=(3,3)
c = a * b
c.shape

(3, 3)

## Calculating Total Calories

In [2]:
cal = A.sum(axis=0)
print(str(cal))

[ 58.2 239.  155.4  77.7]


## Calculating Calorie Percentages

In [3]:
percentage = A/cal.reshape(1,4)
print(str(percentage))

[[0.96219931 0.         0.02831403 0.88545689]
 [0.02061856 0.43514644 0.33462033 0.1029601 ]
 [0.01718213 0.56485356 0.63706564 0.01158301]]
