# Python Jupyter Vectors

## Generate Random Numbers

In [6]:
import numpy as np

a = np.random.randn(5)

In [7]:
print(str(a))

[ 0.13834919 -0.76225135  2.01571247  0.25299277 -1.91348632]


In [9]:
print(a.shape)

(5,)


In [11]:
print(a.T)

[ 0.13834919 -0.76225135  2.01571247  0.25299277 -1.91348632]


In [12]:
print(np.dot(a, a.T))

8.388699644410707


In [14]:
a = np.random.randn(5,1)
print(str(a))

[[-0.39163402]
 [-0.00763563]
 [ 2.58833286]
 [ 0.5486866 ]
 [ 1.16231368]]


In [15]:
print(a.T)

[[-0.39163402 -0.00763563  2.58833286  0.5486866   1.16231368]]


In [16]:
print(np.dot(a, a.T))

[[ 1.53377209e-01  2.99037143e-03 -1.01367922e+00 -2.14884343e-01
  -4.55201584e-01]
 [ 2.99037143e-03  5.83028034e-05 -1.97635449e-02 -4.18956638e-03
  -8.87499400e-03]
 [-1.01367922e+00 -1.97635449e-02  6.69946702e+00  1.42018357e+00
   3.00845470e+00]
 [-2.14884343e-01 -4.18956638e-03  1.42018357e+00  3.01056990e-01
   6.37745946e-01]
 [-4.55201584e-01 -8.87499400e-03  3.00845470e+00  6.37745946e-01
   1.35097309e+00]]
